apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: adamoctoclose/octoretail-frontend:#{Octopus.Release.Number}
        ports:
        - containerPort: #{Project.frontend.port}
        env:
        - name: PORT
          value: "#{Project.frontend.port}"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: #{Project.frontend.port}
      targetPort: #{Project.frontend.port}
  type: LoadBalancer
